# Generated by Django 4.2 on 2024-10-23 10:10

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'This username is already taken.'}, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(error_messages={'unique': 'An account with this email already exists.'}, max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='idx_accounts_email'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['username'], name='idx_accounts_username'),
        ),
    ]
